server:
  port: 10807

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: passw0rd
    # 使用druid数据源
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  # configLocation: classpath:mybatis/mybatis-config.xml
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: cn.hacz.edu.*.entity

# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql