server:
  port: 10807

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: passw0rd
    # 使用druid数据源
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml # 对应的mapper的xml文件
  type-aliases-package: cn.hacz.edu.entity,cn.hacz.edu.vo  # 实体扫描，多个package用逗号或者分号分隔，mapper文件不用写全路径
  configuration:
    cache-enabled: true # 启用或禁用缓存
    lazy-loading-enabled: true # 关联对象都会即时加载
    multiple-result-sets-enabled: true # 允许或不允许多种结果集从一个单独的语句中返回
    map-underscore-to-camel-case: false   # 驼峰风格命名
    lazy-load-trigger-methods: equals,clone,hashCode,toString  # 延迟加载触发方法

# pageHelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql