server:
  port: 1801
spring:
  kafka:
    bootstrap-servers: 211.144.5.80:9092
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: consumer-group
      auto-offset-reset: latest
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-commit-interval: 100
      enable-auto-commit: true
  output:
    ansi:
      enabled: detect
debug: true