server:
  port: 10409
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    username: root
    password: 123654
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///boot
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect