# 服务基础
server:
  port: 11002
  servlet:
    context-path: /job
# 持久化配置
spring:
  datasource:
    username: root
    password: passw0rd
    url: jdbc:mysql:///test
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      format_sql: true
# 任务调度
xxl:
  job:
    executor:
      logpath: /data/applogs/xxl-job/jobhandler
      appname: xxl-job-executor-sample
      port: 9999
      logretentiondays: -1
      ip:
    admin:
      addresses: http://127.0.0.1:8042/xxl-job-admin
    accessToken: