server:
  port: 9090

# redis 集群配置  single
spring:
  redis:
    cluster:
      nodes: 192.168.252.53:7000,192.168.252.53:7001,192.168.252.53:7002,192.168.252.53:7003,192.168.252.53:7004,192.168.252.53:7005
      timeout: 6000ms # 连接池超时时间（毫秒）
    # 密码没有可以不填
    password:
    database: 0 # 数据库索引
    lettuce:
      pool:
        max-active: 8 # 连接池最大活跃连接数（使用负值表示没有限制）
        max-idle: 8 # 连接池最大空闲连接数
        max-wait: -1ms # 连接池最大阻塞等待时间 毫秒（使用负值表示没有限制）
        min-idle: 0  #最小空闲连接数