server:
  port: 10901
  tomcat:
    uri-encoding: utf-8
jasypt:
  encryptor:
    password: foo
spring:
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接密码（默认为空）
    password:
    # Redis服务器地址
    host: 192.168.100.11
    # Redis服务器连接端口
    port: 6379
    timeout: 1000
    # 变更后 增加了一层jedis
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  datasource:
    username: root
    password: passw0rd
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useOldAliasMetadataBehavior=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update