server:
  port: 9696
  servlet:
    context-path: /ssh
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30

spring:
  application:
    name: project-ssh
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

jasypt:
  encryptor:
    password: guodd

logging:
  config: classpath:logback-spring.xml
  level:
    cn.hacz.edu.modules.system.controller: 'off'

props:
  simple-prop: props

token:
  header: token           # token 请求头的名字
  secret: secret         # token 加密密钥
  expiration: 604800    # token 过期时间，以秒为单位，604800 是 一星期

secret:
  key: test

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
