server:
  port: 10902
  tomcat:
    uri-encoding: utf-8
jasypt:
  encryptor:
    password: foo
spring:
  datasource:
    username: root
    password: 123654
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///boot
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
  data:  # MongoDB数据库配置
    mongodb:
      host: 'ENC(y3jjpYbJcYNd0nq2OT7jT87m7A7H+cAt)'
      port: 27017
      database: guod