server:
  port: 10902
  tomcat:
    uri-encoding: utf-8
jasypt:
  encryptor:
    password: foo
spring:
  datasource:
    username: root
    password: passw0rd
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///test
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
  data:  # MongoDB数据库配置
    mongodb:
      host: 10.248.2.12
      port: 27017
      database: demo